<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dídac Capó">

<title>¿El apoyo familiar influye a los resultados académicos?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Sol.Didac_files/libs/clipboard/clipboard.min.js"></script>
<script src="Sol.Didac_files/libs/quarto-html/quarto.js"></script>
<script src="Sol.Didac_files/libs/quarto-html/popper.min.js"></script>
<script src="Sol.Didac_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Sol.Didac_files/libs/quarto-html/anchor.min.js"></script>
<link href="Sol.Didac_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Sol.Didac_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Sol.Didac_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Sol.Didac_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Sol.Didac_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#hipotesis-y-objetivos-parte-i" id="toc-hipotesis-y-objetivos-parte-i" class="nav-link" data-scroll-target="#hipotesis-y-objetivos-parte-i">Hipotesis y objetivos (Parte I)</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general">Objetivo general</a></li>
  <li><a href="#objetivos-secundários" id="toc-objetivos-secundários" class="nav-link" data-scroll-target="#objetivos-secundários">Objetivos secundários</a></li>
  </ul></li>
  <li><a href="#creación-y-descripción-de-la-base-de-datos-parte-ii" id="toc-creación-y-descripción-de-la-base-de-datos-parte-ii" class="nav-link" data-scroll-target="#creación-y-descripción-de-la-base-de-datos-parte-ii">Creación y descripción de la base de datos (Parte II)</a>
  <ul class="collapse">
  <li><a href="#simulación-de-los-datos" id="toc-simulación-de-los-datos" class="nav-link" data-scroll-target="#simulación-de-los-datos">Simulación de los datos</a></li>
  </ul></li>
  <li><a href="#análisis-descriptivo-parte-iii" id="toc-análisis-descriptivo-parte-iii" class="nav-link" data-scroll-target="#análisis-descriptivo-parte-iii">Análisis descriptivo (Parte III)</a></li>
  <li><a href="#aplicación-de-pruebas-estadísticas" id="toc-aplicación-de-pruebas-estadísticas" class="nav-link" data-scroll-target="#aplicación-de-pruebas-estadísticas">Aplicación de pruebas estadísticas</a>
  <ul class="collapse">
  <li><a href="#modelizar-la-variable-nivel_apoyo_familiar-parte-iv" id="toc-modelizar-la-variable-nivel_apoyo_familiar-parte-iv" class="nav-link" data-scroll-target="#modelizar-la-variable-nivel_apoyo_familiar-parte-iv">Modelizar la variable nivel_apoyo_familiar (Parte IV)</a></li>
  <li><a href="#modelo-de-regresión-multivariante-para-media_calificaciones-partev" id="toc-modelo-de-regresión-multivariante-para-media_calificaciones-partev" class="nav-link" data-scroll-target="#modelo-de-regresión-multivariante-para-media_calificaciones-partev">Modelo de regresión multivariante para media_calificaciones Parte(V)</a></li>
  <li><a href="#contraste-de-hipótesis-parte-vi" id="toc-contraste-de-hipótesis-parte-vi" class="nav-link" data-scroll-target="#contraste-de-hipótesis-parte-vi">Contraste de hipótesis (Parte VI)</a></li>
  </ul></li>
  <li><a href="#conclusiones-o-recomendaciones-parte-vii" id="toc-conclusiones-o-recomendaciones-parte-vii" class="nav-link" data-scroll-target="#conclusiones-o-recomendaciones-parte-vii">Conclusiones o recomendaciones (Parte VII)</a></li>
  <li><a href="#bibliografia" id="toc-bibliografia" class="nav-link" data-scroll-target="#bibliografia">Bibliografia</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">¿El apoyo familiar influye a los resultados académicos?</h1>
<p class="subtitle lead">20582 - Análisis de Datos para el GMAT</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dídac Capó </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><a href="https://github.com/WatCadet/Taller-de-repaso-para-el-Parcial-I">Enlace al repositorio de Github</a></p>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>En este análisis se realizará un estudio multivariante a partir de datos recolectados de estudiantes. El objetivo es determinar si el nivel de apoyo que los estudiantes sienten en casa en relación con sus estudios tiene un impacto significativo en su desempeño académico. A través de técnicas estadísticas multivariantes, se analizarán diversas variables relacionadas con el entorno familiar y los resultados escolares para identificar posibles patrones que permitan entender mejor esta influencia.</p>
</section>
<section id="hipotesis-y-objetivos-parte-i" class="level2">
<h2 class="anchored" data-anchor-id="hipotesis-y-objetivos-parte-i">Hipotesis y objetivos (Parte I)</h2>
<p>La hipótesis a investigar es la siguiente: “Los estudiantes que reciben apoyo familiar habitualmente en sus estudios tienden a obtener mejores resultados académicos”. Esta hipótesis se basa en la idea de que el apoyo familiar, ya sea mediante ayuda con las tareas, motivación o seguimiento, podría tener un impacto positivo en el rendimiento académico del alumno, facilitando el aprendizaje y fortaleciendo la disciplina y la responsabilidad del estudiante.</p>
<section id="objetivo-general" class="level3">
<h3 class="anchored" data-anchor-id="objetivo-general">Objetivo general</h3>
<ul>
<li>Evaluar el impacto del apoyo familiar en el rendimiento académico de los estudiantes.</li>
</ul>
</section>
<section id="objetivos-secundários" class="level3">
<h3 class="anchored" data-anchor-id="objetivos-secundários">Objetivos secundários</h3>
<ul>
<li><p>Medir la percepción de los estudiantes sobre el apoyo que reciben en casa.</p></li>
<li><p>Cuantificar el rendimiento académico y ver si se relaciona con el apoyo familiar.</p></li>
<li><p>Considerar otros factores que puedan afectar el rendimiento académico.</p></li>
<li><p>Verificar si el rendimiento académico y el apoyo familiar cambian según el nivel educativo de los padres.</p></li>
</ul>
</section>
</section>
<section id="creación-y-descripción-de-la-base-de-datos-parte-ii" class="level2">
<h2 class="anchored" data-anchor-id="creación-y-descripción-de-la-base-de-datos-parte-ii">Creación y descripción de la base de datos (Parte II)</h2>
<p>Las variables que usaremos para analizar nuestra hipotesis son las siguientes:</p>
<section id="variables-nominales" class="level4">
<h4 class="anchored" data-anchor-id="variables-nominales">Variables nominales:</h4>
<ul>
<li><em>Género</em>, con niveles: Masculino y Femenino</li>
<li><em>Tipo de escuela</em>, con niveles: Pública y Privada</li>
</ul>
</section>
<section id="variables-ordinales" class="level4">
<h4 class="anchored" data-anchor-id="variables-ordinales">Variables ordinales:</h4>
<ul>
<li><em>Nivel de apoyo familiar</em>, con niveles: Bajo, Medio y Alto. Percepción própia del estudiante sobre el apoyo familiar que recibe.</li>
<li><em>Motivación académica</em> con niveles: Muy Baja, Baja, Media, Alta y Muy Alta.</li>
<li><em>Nivel de interés en las materias</em> con niveles: Muy Bajo, Bajo, Medio, Alto y Muy Alto. El grado de interés del estudiante en las asignaturas.</li>
</ul>
</section>
<section id="variables-cuantitativas" class="level4">
<h4 class="anchored" data-anchor-id="variables-cuantitativas">Variables cuantitativas:</h4>
<ul>
<li><em>Horas de apoyo familiar</em>, medida en horas por semana.</li>
<li><em>Media de calificaciones</em>, mediada en una escala de 1 a 10. Calificaciones del estudiante en el último semestre.</li>
<li><em>Horas de estudio individual</em>, medida en horas por semana.</li>
<li><em>Tiempo de transporte diario</em>, medida en minutos. Tiempo medio que el estudiante dedica al traslado a la escuela diariamente.</li>
</ul>
</section>
<section id="simulación-de-los-datos" class="level3">
<h3 class="anchored" data-anchor-id="simulación-de-los-datos">Simulación de los datos</h3>
<p>Definimos las medias y matriz de covarianza para las variables cuantitativas. El vector de medias sigue el siguiente orden: media de horas de apoyo familiar, media de calificaciones, media de horas de estudio individual, media de minutos de transporte.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="fl">6.5</span>, <span class="fl">7.5</span>, <span class="dv">15</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>covarianza <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>, <span class="fl">1.5</span>, <span class="fl">0.5</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                       <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="fl">0.2</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">1.5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="fl">0.7</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">0.5</span>, <span class="fl">0.2</span>, <span class="fl">0.7</span>, <span class="dv">6</span>), </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Establecer una semilla para reproducibilidad</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar datos cuantitativos</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>datos_numericos <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(<span class="dv">100</span>, <span class="at">mu =</span> media, <span class="at">Sigma =</span> covarianza)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar los valores de promedio de calificaciones a la escala de 1 a 10</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>datos_numericos[,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">pmin</span>(<span class="fu">pmax</span>(<span class="fu">round</span>(datos_numericos[,<span class="dv">2</span>], <span class="dv">1</span>), <span class="dv">1</span>), <span class="dv">10</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear la tabla de datos con las variables definidas</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>data_apoyo_familiar <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">h_apoyo_familiar =</span> <span class="fu">round</span>(datos_numericos[,<span class="dv">1</span>], <span class="dv">1</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">media_calificaciones =</span> datos_numericos[,<span class="dv">2</span>],</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">h_estudio_individual =</span> <span class="fu">round</span>(datos_numericos[,<span class="dv">3</span>], <span class="dv">1</span>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">tiempo_transporte =</span> <span class="fu">round</span>(datos_numericos[,<span class="dv">4</span>]),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">tipo_escuela =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Pública"</span>, <span class="st">"Privada"</span>), <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">genero =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Masculino"</span>, <span class="st">"Femenino"</span>), <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel_apoyo_familiar =</span> <span class="fu">ordered</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Bajo"</span>, <span class="st">"Medio"</span>, <span class="st">"Alto"</span>)),</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">motivacion_academica =</span> <span class="fu">ordered</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Muy Baja"</span>, <span class="st">"Baja"</span>, <span class="st">"Media"</span>, <span class="st">"Alta"</span>, <span class="st">"Muy Alta"</span>)),</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel_interes_materias =</span> <span class="fu">ordered</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Muy Bajo"</span>, <span class="st">"Bajo"</span>, <span class="st">"Medio"</span>, <span class="st">"Alto"</span>, <span class="st">"Muy Alto"</span>))</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mostramos las 6 primeras filas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_apoyo_familiar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  h_apoyo_familiar media_calificaciones h_estudio_individual tiempo_transporte
1              1.9                  5.0                  8.7                11
2              7.4                  6.7                  9.1                14
3              5.2                  6.3                  4.6                16
4              8.5                  7.2                  5.9                11
5              2.3                  5.2                  7.8                16
6              3.8                  6.1                  9.1                15
  tipo_escuela    genero nivel_apoyo_familiar motivacion_academica
1      Privada  Femenino                Medio                 Baja
2      Privada Masculino                 Bajo             Muy Alta
3      Privada Masculino                Medio                Media
4      Pública Masculino                 Bajo             Muy Baja
5      Privada  Femenino                Medio                Media
6      Privada Masculino                Medio             Muy Baja
  nivel_interes_materias
1                   Alto
2                   Alto
3                  Medio
4                   Bajo
5               Muy Bajo
6               Muy Bajo</code></pre>
</div>
</div>
<p>Vamos a añadir dos variables más, extraidas del conjunto de datos <code>Students_Performance.csv</code> que podemos encontrar en el siguiente <a href="https://www.kaggle.com/datasets/muhammadroshaanriaz/students-performance-dataset-cleaned?resource=download">enlace</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>students_data<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"Students_Performance.csv"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">","</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> students_data <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(parental_level_of_education, lunch)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Tomar una muestra aleatoria de 100 observaciones</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># Aseguramos reproducibilidad</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>sampled_data <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Veamos que niveles tienen nuestras dos nuevas variables y su frecuencia:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sampled_data <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(parental_level_of_education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  parental_level_of_education  n
1          associate's degree 22
2           bachelor's degree 13
3                 high school 20
4             master's degree  6
5                some college 22
6            some high school 17</code></pre>
</div>
</div>
<p>Vamos a agrupar en solo dos clases:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sampled_data <span class="ot">&lt;-</span> sampled_data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Educacion_Padres =</span> <span class="fu">case_when</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    parental_level_of_education <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"some high school"</span>, <span class="st">"high school"</span>) <span class="sc">~</span> <span class="st">"básicos"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    parental_level_of_education <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"associate's degree"</span>, <span class="st">"bachelor's degree"</span>, <span class="st">"master's degree"</span>,<span class="st">"some college"</span>) <span class="sc">~</span> <span class="st">"superiores"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sampled_data <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(lunch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lunch  n
1     0 39
2     1 61</code></pre>
</div>
</div>
<p>Las nuevas variables son:</p>
<ul>
<li><p><em>Educación Padres</em>: Indica el nivel educativo de la familia del estudiante. Es una variable nominal con dos niveles: Estudios básicos y Estudios superiores.</p></li>
<li><p><em>Lunch</em>: Muestra si los estudiantes reciben almuerzo lo cual es a menudo un indicador socioeconómico. Es una variable binària con dos valores 1, si si recibe y 0, si no recibe.</p></li>
</ul>
<p>Finalmente, añadimos al conjunto de datos inicial nuestras dos nuevas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un nuevo dataset con las columnas que quieres añadir</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>nuevas_columnas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Lunch =</span> sampled_data<span class="sc">$</span>lunch, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Educacion_Padres =</span> sampled_data<span class="sc">$</span>Educacion_Padres</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Unir los datasets manteniendo los nombres de las columnas</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>data_apoyo_familiar <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(data_apoyo_familiar, nuevas_columnas)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_apoyo_familiar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  h_apoyo_familiar media_calificaciones h_estudio_individual tiempo_transporte
1              1.9                  5.0                  8.7                11
2              7.4                  6.7                  9.1                14
3              5.2                  6.3                  4.6                16
4              8.5                  7.2                  5.9                11
5              2.3                  5.2                  7.8                16
6              3.8                  6.1                  9.1                15
  tipo_escuela    genero nivel_apoyo_familiar motivacion_academica
1      Privada  Femenino                Medio                 Baja
2      Privada Masculino                 Bajo             Muy Alta
3      Privada Masculino                Medio                Media
4      Pública Masculino                 Bajo             Muy Baja
5      Privada  Femenino                Medio                Media
6      Privada Masculino                Medio             Muy Baja
  nivel_interes_materias Lunch Educacion_Padres
1                   Alto     1       superiores
2                   Alto     0          básicos
3                  Medio     0          básicos
4                   Bajo     1       superiores
5               Muy Bajo     0          básicos
6               Muy Bajo     1          básicos</code></pre>
</div>
</div>
</section>
</section>
<section id="análisis-descriptivo-parte-iii" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo-parte-iii">Análisis descriptivo (Parte III)</h2>
<p>Para realizar el análisis descriptivo multivariante usaremos un <code>ggpairs</code>. Lo haremos solo de las variables que creemos que son más interesantes para alcanzar nuestros objetivos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>subset1_data_apoyo_familiar <span class="ot">&lt;-</span> data_apoyo_familiar <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(h_apoyo_familiar, media_calificaciones, h_estudio_individual, genero)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(subset1_data_apoyo_familiar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sol.Didac_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analizemos el siguiente gráfico de dispersión que nos permite examinar visualmente las relaciones entre varias variables numéricas y categóricas relacionadas con el apoyo familiar y el rendimiento académico.</p>
<p>En la <strong>Diagonal principal</strong> están las distribuciones individuales (histogramas y curvas de densidad) de cada variable numérica:</p>
<ul>
<li><p>h_apoyo_familiar: Distribución ligeramente sesgada a la izquierda, indicando que la mayoría de los valores de apoyo familiar están concentrados entre 4 y 8 horas.</p></li>
<li><p>media_calificaciones: Distribución aproximadamente normal con una media en torno a <span class="math inline">\(7\)</span>, aunque ligeramente sesgada hacia la derecha.</p></li>
<li><p>h_estudio_individual: Distribución aproximadamente normal con una media en torno a <span class="math inline">\(7.5\)</span>.</p></li>
<li><p>género: histograma donde vemos que hay una ligera predominancia de estudiantes masculinos.</p></li>
</ul>
<p>Veamos ahora las <strong>relaciones entre variables cuantitativas</strong>:</p>
<ul>
<li><p>h_apoyo_familiar y media_calificaciones: La celda muestra un valor de correlación de 0.460, lo cual indica una correlación positiva. Esto sugiere que los estudiantes que reciben más horas de apoyo familiar tienden a tener mejores calificaciones en promedio. La nube de puntos en esta celda refuerza esta relación: se observa una tendencia ascendente entre horas de apoyo familiar y calificaciones.</p></li>
<li><p>h_apoyo_familiar y h_estudio_individual: La correlación es de 0.336, mostrando una correlación positiva. Esto sugiere que los estudiantes que reciben más apoyo familiar también tienden a dedicar más horas al estudio individual. La nube de puntos refleja una tendencia ascendente ligera entre el apoyo familiar y el tiempo de estudio individual.</p></li>
<li><p>media_calificaciones y h_estudio_individual: La correlación entre estas variables es 0.286, indicando una correlación positiva aunque más baja que las anteriores. Esto sugiere que los estudiantes que dedican más horas al estudio individual tienden a obtener calificaciones ligeramente más altas. La nube de puntos es más dispersa, pero hay una ligera tendencia positiva.</p></li>
</ul>
<p>Aunque no sea el objetivo principal del anàlisis veamos por encima las diferéncias por sexo:</p>
<p><strong>Relación entre las variables cuantitativas y género</strong></p>
<p>Los boxplots muestran que tanto hombres como mujeres reciben niveles de apoyo familiar similares. No hay una diferencia significativa en la mediana ni en la distribución general. De la misma manera, los boxplots de calificaciones y de horas de estudio individual también son similares entre géneros.</p>
<p><strong>Interpretación global en relación con el objetivo</strong> La correlación positiva respalda la hipótesis de que mayores niveles de apoyo familiar pueden influir positivamente en los resultados académicos de los estudiantes. Además la correlación positiva entre el apoyo familiar y el tiempo de estudio individual sugiere que los estudiantes con más apoyo familiar no solo tienen mejores calificaciones, sino que también están más motivados.</p>
<p>Veamos ahora solo para las variables cuantitativas, que varianza generalizada y varianza total tienen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>subset2_data_apoyo_familiar <span class="ot">&lt;-</span> data_apoyo_familiar <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(h_apoyo_familiar, media_calificaciones, h_estudio_individual, tiempo_transporte)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Las definiciones de varianza generalizada y variación total són las siguientes,repectivamente:</p>
<p><span class="math display">\[|S| = \prod_i^p \lambda_i\]</span> <span class="math display">\[Tr(S)= \sum_i^p \lambda_i\]</span> donde los <span class="math inline">\(\lambda_i\)</span> són los valores propios de la matriz de covarianzas <span class="math inline">\(S\)</span>. Saquemos los valores propios de <span class="math inline">\(S\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> <span class="fu">cov</span>(subset2_data_apoyo_familiar)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>valores_propios <span class="ot">&lt;-</span> <span class="fu">eigen</span>(S)<span class="sc">$</span>values</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>valores_propios</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.094996 4.617015 2.946894 1.783450</code></pre>
</div>
</div>
<p>Por tanto, la varianza generalizada es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(valores_propios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 196.4279</code></pre>
</div>
</div>
<p>Y, la variación total:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(valores_propios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.44235</code></pre>
</div>
</div>
<p>La variación total representa la dispersión individual de las variables. Es decir, mide cuánto varía cada variable sin considerar las relaciones entre ellas(ignora las covarianzas). Mientras que la varianza generalizada mide la variabilidad conjunta de las variables, es decir, cuánto varían las variables juntas. En este caso, la varianza generalizada es <span class="math inline">\(196.4\)</span> y la variación total <span class="math inline">\(17.4\)</span>. Esto indica que las cuatro variables tienen una cantidad poco significativa de variación individual(como refleja la variación total), aunque hay una gran dispersión conjunta. Esto indica que no hay redundancia entre las variables.</p>
</section>
<section id="aplicación-de-pruebas-estadísticas" class="level2">
<h2 class="anchored" data-anchor-id="aplicación-de-pruebas-estadísticas">Aplicación de pruebas estadísticas</h2>
<section id="modelizar-la-variable-nivel_apoyo_familiar-parte-iv" class="level3">
<h3 class="anchored" data-anchor-id="modelizar-la-variable-nivel_apoyo_familiar-parte-iv">Modelizar la variable nivel_apoyo_familiar (Parte IV)</h3>
<p>Primero, necesitamos calcular las probabilidades de que un estudiante pertenezca a cada una de las categorías del nivel de apoyo familiar percibido por el alumno</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>probabilidades_apoyo_familiar <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data_apoyo_familiar<span class="sc">$</span>nivel_apoyo_familiar))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>probabilidades_apoyo_familiar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Bajo Medio  Alto 
 0.33  0.34  0.33 </code></pre>
</div>
</div>
<p>Ahora que tenemos las probabilidades de las categorías, podemos modelar la variable nivel_apoyo_familiar usando una distribución multinomial. Calculemos la probabilidad de que, en una muestra de tamaño 20, al menos 10 estudiantes tengan un alto nivel de apoyo familiar (categoría “Alto”). Podemos realizar una simulación para obtener la probabilidad de que ocurra este evento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pb <span class="ot">&lt;-</span> probabilidades_apoyo_familiar[<span class="st">"Bajo"</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>pm <span class="ot">&lt;-</span> probabilidades_apoyo_familiar[<span class="st">"Medio"</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>pa <span class="ot">&lt;-</span> probabilidades_apoyo_familiar[<span class="st">"Alto"</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>simulaciones_apoyo <span class="ot">&lt;-</span> <span class="fu">rmultinom</span>(<span class="dv">10000</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="fu">c</span>(pb, pm, pa))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>evento_interes_apoyo <span class="ot">&lt;-</span> <span class="fu">sum</span>(simulaciones_apoyo[<span class="dv">3</span>, ] <span class="sc">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>probabilidad_evento_apoyo <span class="ot">&lt;-</span> evento_interes_apoyo <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>probabilidad_evento_apoyo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0856</code></pre>
</div>
</div>
<p>Una probabilidad de 0.0856 indica que solo en el 8.56% de las muestras de 20 estudiantes se observa que al menos 10 tienen un alto nivel de apoyo familiar, lo que sugiere que este nivel de apoyo no es común en la población estudiada. Esto implica que un alto apoyo familiar podría no ser la norma, afectando su impacto en el rendimiento académico.</p>
</section>
<section id="modelo-de-regresión-multivariante-para-media_calificaciones-partev" class="level3">
<h3 class="anchored" data-anchor-id="modelo-de-regresión-multivariante-para-media_calificaciones-partev">Modelo de regresión multivariante para media_calificaciones Parte(V)</h3>
<p>Veamos las 6 primeras filas de la tabla de variables cuantitativas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset2_data_apoyo_familiar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  h_apoyo_familiar media_calificaciones h_estudio_individual tiempo_transporte
1              1.9                  5.0                  8.7                11
2              7.4                  6.7                  9.1                14
3              5.2                  6.3                  4.6                16
4              8.5                  7.2                  5.9                11
5              2.3                  5.2                  7.8                16
6              3.8                  6.1                  9.1                15</code></pre>
</div>
</div>
<p>Queremos explicar la variable <code>media_calificaciones</code> a partir de las otras tres. Consideremos que queremos estimar los parámetros <span class="math inline">\(\beta_0, \beta_1,\beta_2\)</span> y <span class="math inline">\(\beta_3\)</span> del modelo de regresión lineal múltiple:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 \beta_3 X_3 + \epsilon,\]</span></p>
<p>donde <span class="math inline">\(Y\)</span> representa la media en las calificaciones, <span class="math inline">\(X_1\)</span> las horas de apoyo familiar, <span class="math inline">\(X_2\)</span> las horas de estudio individual, <span class="math inline">\(X_3\)</span> el tiempo de transporte , y <span class="math inline">\(\epsilon\)</span> es el término de error.</p>
<p>Dado que estamos interesados en estimar los parámetros <span class="math inline">\(\beta = (\beta_0, \beta_1, \beta_2, \beta_3)\)</span>, necesitamos derivar la función de verosimilitud en términos de estos parámetros y luego obtener la función de score tomando la derivada de la log-verosimilitud con respecto a $ $.</p>
<p>Podemos escribir el modelo en forma matricial como:</p>
<p><span class="math display">\[Y = X \beta + \epsilon,\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> es el vector de media de calificaciones</p></li>
<li><p><span class="math inline">\(X\)</span> es la matriz de las otras tres variables con una columna de una añadida al principio</p></li>
<li><p><span class="math display">\[\beta = \begin{pmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \beta_3 \end{pmatrix},\]</span></p></li>
<li><p><span class="math display">\[\epsilon \sim \mathcal{N}(0, \sigma^2 I)\]</span> es el vector de términos de error, que sigue una distribución normal con media cero y varianza $ ^2 $.</p></li>
</ul>
<p>Dado que el término de error <span class="math inline">\(\epsilon\)</span> sigue una distribución normal, el vector <span class="math inline">\(Y\)</span> también sigue una distribución normal, con media <span class="math inline">\(X \beta\)</span> y varianza <span class="math inline">\(\sigma^2 I\)</span>:</p>
<p><span class="math display">\[Y \sim \mathcal{N}(X \beta, \sigma^2 I).\]</span> Hagamos el modelo de regresión multivariante:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>modelo_regresion <span class="ot">&lt;-</span> <span class="fu">lm</span>(media_calificaciones <span class="sc">~</span> h_apoyo_familiar <span class="sc">+</span> h_estudio_individual <span class="sc">+</span>tiempo_transporte , <span class="at">data =</span> subset2_data_apoyo_familiar)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver los resultados del modelo</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_regresion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = media_calificaciones ~ h_apoyo_familiar + h_estudio_individual + 
    tiempo_transporte, data = subset2_data_apoyo_familiar)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5374 -1.0679  0.0983  1.0578  2.8763 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           3.18727    0.98743   3.228  0.00171 ** 
h_apoyo_familiar      0.32655    0.07772   4.202 5.93e-05 ***
h_estudio_individual  0.10831    0.07823   1.385  0.16941    
tiempo_transporte     0.05119    0.06290   0.814  0.41778    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.49 on 96 degrees of freedom
Multiple R-squared:  0.2367,    Adjusted R-squared:  0.2129 
F-statistic: 9.925 on 3 and 96 DF,  p-value: 9.242e-06</code></pre>
</div>
</div>
<p>Analizemos los resultados dados:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span>: El intercepto és <span class="math inline">\(3.18\)</span> que es el valor de cuando todas las variables independientes son 0.</p></li>
<li><p><span class="math inline">\(\beta_1 = 0.33\)</span> : Por cada hora apoyo familiar adicional de estudio, el rendimiento académico aumenta en 0.33 puntos. Esto sugiere que existe una relación positiva entre el apoyo familiar y el rendimiento académico.</p></li>
<li><p><span class="math inline">\(\beta_2 = 0.11\)</span> Cada hora adicional de estudio individual está asociada con un aumento de 0.11 puntos en el rendimiento académico. Aunque esta relación también es positiva, su impacto es menor que el de las horas de apoyo familiar.</p></li>
<li><p><span class="math inline">\(\beta_3 = 0.05\)</span>: El coeficiente es positivo, lo que sugiere que más tiempo de traslado está asociado con una mejora en el rendimiento académico, lo cual es un poco contraintuitivo. Aunque como el valor es tan pequeño, probablemente no tenga un impacto significativo en el rendimiento académico.</p></li>
<li><p>Vemos por los p-valores que la variable que tiene un efecto más significativo sobre media_calificaciones es h_apoyo_familiar con un valor <span class="math inline">\(p = 5.93\cdot10^{-5}\)</span>. Las otras dos no tienen valor significativo.</p></li>
<li><p>El valor de <span class="math inline">\(R^2\)</span> de 0.2367 indica que el modelo explica solo el 23.67% de la variabilidad del rendimiento académico a partir de las variables independientes consideradas. Esto implica que gran parte de la variabilidad del rendimiento académico no está siendo explicada por las variables del modelo. Esto sugiere que podría ser útil incluir más variables en el modelo</p></li>
</ul>
<p>En resumen, aunque las 3 variables están relacionadas con el rendimiento académico, la capacidad del modelo para predecir dicho rendimiento es limitada.</p>
<p>Por otro lado, la función de score en términos de <span class="math display">\[\beta\]</span> es:</p>
<p><span class="math display">\[
Score(\beta) = \frac{1}{\sigma^2} X^T (Y - X \beta).
\]</span></p>
<p>Veamos si esta es o no 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> subset2_data_apoyo_familiar <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(h_apoyo_familiar, h_estudio_individual, tiempo_transporte)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(X)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>columna_unos <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(X))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(columna_unos, X)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.18</span>,<span class="fl">0.33</span>,<span class="fl">0.11</span>,<span class="fl">0.05</span>) </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> X <span class="sc">%*%</span> B <span class="sc">+</span> e </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>Score_sin_sigma <span class="ot">=</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> (Y <span class="sc">-</span> X <span class="sc">%*%</span> B)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>Score_sin_sigma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           [,1]
columna_unos           9.040591
h_apoyo_familiar      49.232769
h_estudio_individual  58.854255
tiempo_transporte    157.740319</code></pre>
</div>
</div>
<p>Como la función de score es diferente de cero, indica que al cambiar los valores de <span class="math inline">\(\beta\)</span>, podríamos encontrar un ajuste de mayor verosimilitud para el modelo.</p>
<p>Este ajuste es fundamental para modelar y entender el efecto de cada factor en el rendimiento academico, lo cual podría ayudar a dar recomendaciones a las familias para ayudar al rendimiento académico de sus hijos.</p>
</section>
<section id="contraste-de-hipótesis-parte-vi" class="level3">
<h3 class="anchored" data-anchor-id="contraste-de-hipótesis-parte-vi">Contraste de hipótesis (Parte VI)</h3>
<p>El objetivo de esta sección es comparar las medias de dos grupos en varias variables a la vez. En nuestro caso, los dos grupos estarán divididos según el nivel de estudios de los padres. Las variables que vamos a analizar en estos dos grupos son el nivel de apoyo familiar y el promedio de calificaciones. Definamos todo lo necesario para llevar a cabo este análisis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> data_apoyo_familiar <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Educacion_Padres <span class="sc">==</span> <span class="st">"superiores"</span>) <span class="sc">%&gt;%</span>    </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(h_apoyo_familiar, media_calificaciones)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> data_apoyo_familiar <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Educacion_Padres <span class="sc">==</span> <span class="st">"básicos"</span>) <span class="sc">%&gt;%</span>    </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(h_apoyo_familiar, media_calificaciones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Entonces tenemos que el grupo de alumnos con padres con estudios superiores tiene 63 observaciones y el otro 37.</p>
<p>Definamos los vectores de medias y las matrices de covarianzas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(X1)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(X2)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>S1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(X1)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>S2 <span class="ot">&lt;-</span> <span class="fu">cov</span>(X2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Estimación centrada de la matriz de covarianzas común y su inversa:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>S_tilde <span class="ot">=</span> (<span class="dv">63</span><span class="sc">*</span>S1 <span class="sc">+</span> <span class="dv">37</span><span class="sc">*</span>S2)<span class="sc">/</span><span class="dv">100</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>inv_S_tilde <span class="ot">=</span> <span class="fu">solve</span>(S_tilde)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Distancia de mahalanobis entre las dos muestras:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">t</span>(x1<span class="sc">-</span>x2) <span class="sc">%*%</span> inv_S_tilde <span class="sc">%*%</span> (x1<span class="sc">-</span>x2)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>D</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]
[1,] 0.2124902</code></pre>
</div>
</div>
<p>Estadístico F:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>n1<span class="ot">=</span><span class="dv">63</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>n2<span class="ot">=</span><span class="dv">37</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>p<span class="ot">=</span><span class="dv">2</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>Est_F <span class="ot">=</span> ((n1 <span class="sc">+</span>n2 <span class="sc">-</span><span class="dv">1</span> <span class="sc">-</span>p)<span class="sc">/</span>((n1<span class="sc">+</span>n2<span class="dv">-2</span>)<span class="sc">*</span>(p)))<span class="sc">*</span>((n1<span class="sc">*</span>n2)<span class="sc">/</span>(n1<span class="sc">+</span>n2))<span class="sc">*</span>D</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>F_2_97 <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.99</span>, <span class="at">df1 =</span> <span class="dv">97</span>, <span class="at">df2 =</span> <span class="dv">2</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>p_valor <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(Est_F,<span class="dv">97</span>,<span class="dv">2</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>p_valor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]
[1,] 0.3338499</code></pre>
</div>
</div>
<p>Utilizando el test de hotelling:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>r<span class="ot">=</span><span class="fu">hotelling.test</span>(X1,X2)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test stat:  4.9514 
Numerator df:  2 
Denominator df:  97 
P-value:  0.09158 </code></pre>
</div>
</div>
<p>Dado que en los dos casos el p-valor es major a <span class="math inline">\(0.05\)</span> no existe evidencia suficiente para rechazar <span class="math inline">\(H_0\)</span>. Esto significa que las medias de los dos grupos son iguales.</p>
</section>
</section>
<section id="conclusiones-o-recomendaciones-parte-vii" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones-o-recomendaciones-parte-vii">Conclusiones o recomendaciones (Parte VII)</h2>
<p>Los hallazgos obtenidos son: En la sección 4, observamos que la mayoría de los alumnos perciben que no reciben suficiente apoyo en casa. En la sección 3, encontramos una correlación positiva entre el apoyo familiar y los resultados académicos, y también se identificó que factores como el género y las horas de estudio individual pueden influir en el rendimiento académico, aunque en menos grado. Finalmente, en la sección 6, concluimos que no hay evidencia suficiente para rechazar que las medias de rendimiento académico y el apoyo familiar sean iguales entre los alumnos cuyos padres tienen estudios superiores o básicos. En conclusión, nuestros resultados indican que el apoyo familiar tiene una influencia significativa en el rendimiento académico de los alumnos. Sin embargo, esta influencia no parece estar relacionada con el nivel de formación académica de los padres.</p>
</section>
<section id="bibliografia" class="level2">
<h2 class="anchored" data-anchor-id="bibliografia">Bibliografia</h2>
<ul>
<li><a href="https://www.kaggle.com/datasets/muhammadroshaanriaz/students-performance-dataset-cleaned?resource=download">Data Kaggle</a></li>
<li><a href="https://aprender-uib.github.io/AD/">Aprender R - UIB</a></li>
<li>“Nuevos Métodos de Análisis Multivariante” de Carles M. Cuadras</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>